/-
  RholangBytecode.Basic
  ─────────────────────
  Ground domain, values, names, and processes for rholang 1.2.
  These types are shared between the source language and the bytecode target.

  F1R3FLY.io — Rholang 1.2 Bytecode Interpreter Full Abstraction
  Copyright 2026 Lucius Gregory Meredith
-/

namespace RholangBytecode

/-! ### Name and Process identifiers

  In the Rho calculus, names and processes are mutually recursive:
  every process can be quoted to yield a name, and every name can
  be dereferenced to yield a process. We model this with mutual
  inductive types. -/

/-- Abstract identifiers for fresh names generated by `new`. -/
structure FreshId where
  id : Nat
deriving DecidableEq, Repr, Ord

/-- The ground value domain V, shared between source and target. -/
inductive Val where
  | vInt    : Int → Val
  | vBool   : Bool → Val
  | vString : String → Val
  | vUri    : String → Val
  | vList   : List Val → Val
  | vSet    : List Val → Val        -- represented as sorted list
  | vMap    : List (Val × Val) → Val
  | vName   : Name → Val
  | vProc   : Proc → Val
  | vUnit   : Val
  | vNil    : Val
deriving Repr

/-- Rholang names: either a quoted process or a variable/fresh name. -/
with Name where
  | quoted  : Proc → Name           -- @P
  | free    : FreshId → Name        -- generated by `new`
  | bound   : Nat → Name            -- de Bruijn index
deriving Repr

/-- Rholang 1.2 source processes (abstract syntax). -/
with Proc where
  | nil     : Proc
  | send    : Name → List Proc → Bool → Proc          -- x!(P₁,...,Pₙ) or x!!(...)
  | recv    : List (Name × Pattern) → Proc → Bool → Proc  -- for(y<-x &...){P}
  | par     : Proc → Proc → Proc                      -- P | Q
  | new     : Nat → Proc → Proc                       -- new x₁,...,xₙ in P
  | deref   : Name → Proc                             -- *x
  | matchP  : Proc → List (Pattern × Proc) → Proc     -- match P { pᵢ => Qᵢ }
  | letIn   : GExpr → Proc → Proc                     -- let x = e in P
  | bundle  : BundleKind → Proc → Proc
deriving Repr

/-- Ground expressions (the sequential, deterministic sublanguage). -/
with GExpr where
  | lit     : Val → GExpr
  | var     : Nat → GExpr                              -- local variable ref
  | binop   : BinOp → GExpr → GExpr → GExpr
  | unop    : UnOp → GExpr → GExpr
  | listNew : List GExpr → GExpr
  | setNew  : List GExpr → GExpr
  | mapNew  : List (GExpr × GExpr) → GExpr
  | method  : String → GExpr → List GExpr → GExpr
deriving Repr

/-- Patterns for spatial matching. -/
with Pattern where
  | wildcard  : Pattern
  | pVar      : Nat → Pattern
  | pVal      : Val → Pattern
  | pStruct   : Name → List Pattern → Pattern
  | pAnd      : Pattern → Pattern → Pattern
  | pOr       : Pattern → Pattern → Pattern
  | pNot      : Pattern → Pattern
deriving Repr

/-- Binary operators on ground values. -/
inductive BinOp where
  | add | sub | mul | div | mod_
  | lt | le | gt | ge | eq | neq
  | and_ | or_
  | concat
deriving DecidableEq, Repr

/-- Unary operators. -/
inductive UnOp where
  | neg | not_ | length | toString
deriving DecidableEq, Repr

/-- Bundle capabilities. -/
inductive BundleKind where
  | readOnly | writeOnly | readWrite
deriving DecidableEq, Repr

/-! ### Observable action labels

  The label alphabet for the LTS, shared between source and target.
  This sharing is a key design property enabling full abstraction. -/

/-- Labels on transitions in the labeled transition system. -/
inductive Label where
  | tau     : Label                                    -- silent / internal
  | output  : Name → List Val → Label                  -- x̄⟨v₁,...,vₙ⟩
  | input   : Name → List Val → Label                  -- x(v₁,...,vₙ)
  | scope   : FreshId → Label → Label                  -- (νx)α
deriving Repr

/-- A label is silent (τ). -/
def Label.isTau : Label → Prop
  | .tau => True
  | _   => False

/-- A label is observable (not τ). -/
def Label.isObservable (l : Label) : Prop := ¬ l.isTau

/-! ### Substitution (abstract interface)

  We axiomatize substitution rather than defining it concretely,
  since the full definition requires handling de Bruijn indices
  through all mutual inductive constructors. -/

/-- Substitution of values for bound variables in a process. -/
axiom substProc : Proc → List Val → Proc

/-- Substitution in a name. -/
axiom substName : Name → List Val → Name

/-! ### Structural congruence (axiomatized)

  Rholang's structural congruence equates processes up to
  reordering of parallel components, scope extrusion, etc. -/

/-- Structural congruence on source processes. -/
axiom structCong : Proc → Proc → Prop

notation:50 P " ≡ₛ " Q => structCong P Q

axiom structCong_refl  : ∀ (P : Proc), P ≡ₛ P
axiom structCong_symm  : ∀ (P Q : Proc), P ≡ₛ Q → Q ≡ₛ P
axiom structCong_trans : ∀ (P Q R : Proc), P ≡ₛ Q → Q ≡ₛ R → P ≡ₛ R

-- Par is commutative and associative up to ≡ₛ
axiom par_comm  : ∀ (P Q : Proc), (Proc.par P Q) ≡ₛ (Proc.par Q P)
axiom par_assoc : ∀ (P Q R : Proc),
  (Proc.par (Proc.par P Q) R) ≡ₛ (Proc.par P (Proc.par Q R))
axiom par_nil   : ∀ (P : Proc), (Proc.par P Proc.nil) ≡ₛ P

end RholangBytecode
