Module ArrowCats {
  Theory Arrows() {
    Empty
      Exports { T1; T2; T3; T4; (T1 -> T2); }
      Terms {
        Qux  . T1 ::= "qux" ;
        Quux . T2 ::= "quux" ;
        -- Bar: (T1 -> T2) -> T3
        Bar  . T3 ::= "bar" (Bind t1 T1) "." (t1)T2 ;
        -- Baz: T2 -> T3
        Baz  . T3 ::= "baz" T2 ;
        -- Bee: (T1 -> T2) -> T3
        Bee  . T3 ::= "bee" (T1 -> T2) ;
        -- Foo: ((T1 -> T2) -> T3) -> T4
        Foo  . T4 ::= "foo" (Bind t1t2 (T1 -> T2)) "." (t1t2)T3 ;
      }
  }
  
  theory Arrows()
}